# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('prix', models.FloatField(null=True)),
                ('dateAnnonce', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('image', models.FileField(null=True, upload_to='')),
                ('codeMarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SousModele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('codeModele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Modele')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('codeGouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Gouvernorat')),
            ],
        ),
        migrations.CreateModel(
            name='ZonePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='piecedetachee',
            name='zonePiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ZonePiece'),
        ),
        migrations.AddField(
            model_name='ads',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.PieceDetachee'),
        ),
        migrations.AddField(
            model_name='ads',
            name='sousModele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.SousModele'),
        ),
        migrations.AddField(
            model_name='ads',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ville'),
        ),
    ]
