# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:41
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecedetachee',
            name='image',
        ),
        migrations.AlterField(
            model_name='ads',
            name='dateAnnonce',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date annonce'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=ads.models.upload_location),
        ),
        migrations.AlterField(
            model_name='ads',
            name='sousModele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.SousModele', verbose_name='sous modele'),
        ),
    ]
