# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20161214_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousmodele',
            name='codeModele',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='sousModele',
        ),
        migrations.AddField(
            model_name='ads',
            name='modele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Modele'),
        ),
        migrations.DeleteModel(
            name='SousModele',
        ),
    ]
