# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20161214_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='compte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptes.Compte'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.PieceDetachee'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Ville'),
        ),
    ]
